from numpy import *
arr= array([10, 40 , 60 ,70])
print("example")
print("Array :", arr)
arr1=array([0,1,5,3])
arr2=array([1,4,7,2])
c=arr1>arr2
print("check")
print("check if any one element is same",any(arr1>arr2))
print("check if all element are same",all(arr1>arr2))
c=where(arr1>arr2, arr1 , arr2)
print("Return array:", c)
print("Arr1 elements are as follow:", arr1)
non_zeroele=nonzero(arr1)
print("index of zon-zero element", non_zeroele)
print("Non zero elements are :",arr1[non_zeroele])
print()
print("Use of arange() and view() method of numpy")
a=arange(1,6)
b=a.view()
c=a.copy()
print("Original array:", a)
print("view array:",b)
print("copy array:",c)
b[0]=90
print("after modification")
print("Original array after modification", a)
print("view array after modification", b)
print("Copy array after modification",c)
print("two dimensional array")
arr3=array([[[1,2,3,4],[5,6,7,8]]
            ,[[7,8,9,10],[11,12,13,14]]])
print(arr3)
print("Dimension of the given array",arr3.ndim)
print("Shape of the array:",arr3.shape)
print("Size of the array:",arr3.size)
print("total no of bytes used:",arr3.nbytes)
print("itemsize of element:",arr3.itemsize)
print("reshape the array in hand:", arr3.reshape(2,2,4))
arr4=arr3.flatten()
print(arr4)
print(arr3[0][0][2])
arr5=ones((3,4,2),int)
print(arr5)
R=int(input("enter the noumber of rows:"))
C=int(input("enter the number of columns"))
enteries=list(map(int, input("enter the array elements").split()))
arr2D=array(enteries).reshape(R,C)
arr3D=reshape(arr2D,(C,R))
print("Returned 2D array:",arr2D)
print("Returned 3D array:", arr3D)
for i in range(R):
    for j in range(C):
        print(arr2D[i][j], end=' ')
        
